version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: gubal
    ports:
      - "5432:5432"
  
  bot:
    image: gubal-steward:latest
    depends_on:
      - db
    ports:
      - "4000:4000"
